<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 07.05.2016
 * Time: 10:28
 */

namespace frontend\models;
use yii\db\ActiveRecord;
use frontend\models\Towar;
use Yii;
use yii\base\Model;
class OrderSearch extends Model
{
    public $dwig;
    public $priw;
    public $kat;
 
    public function rules()
    {
        return [
             [['dwig', 'priw', 'kat'], 'required'],

        ];
    }

    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @return ActiveDataProvider
     */
    public function search($params)
    {
       
        $query = Towar::find()
            ->where(['status' => Towar::STATUS_ACTIVE]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()){
            return $dataProvider;
        }
        $query->andFilterWhere([
            'dwig' => $this->dwig,
            'priw' => $this->priw,
            'kat' => $this->kat,
        ]);

        return $dataProvider;
    }
}